"""Initial migration

Revision ID: 85fd2576b10f
Revises: 
Create Date: 2017-06-13 22:11:50.079638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85fd2576b10f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.create_table('auth_device',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('auth_device_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], ),
    sa.PrimaryKeyConstraint('auth_device_id')
    )
    op.create_table('bcrypt_login',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('bcrypt_login_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('hash_algorithm', sa.String(length=512), nullable=False),
    sa.Column('hash_cost', sa.String(length=512), nullable=False),
    sa.Column('salt', sa.String(length=512), nullable=False),
    sa.Column('bcrypt_salt', sa.String(length=512), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('bcrypt_password_hash', sa.String(length=512), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], ),
    sa.PrimaryKeyConstraint('bcrypt_login_id')
    )
    op.create_table('login_device',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('login_device_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], ),
    sa.PrimaryKeyConstraint('login_device_id')
    )
    op.create_table('login_attempt',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('login_attempt_id', sa.Integer(), nullable=False),
    sa.Column('login_at', sa.DateTime(), nullable=True),
    sa.Column('successful', sa.Boolean(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('auth_device_id', sa.Integer(), nullable=True),
    sa.Column('login_device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auth_device_id'], ['auth_device.auth_device_id'], ),
    sa.ForeignKeyConstraint(['login_device_id'], ['login_device.login_device_id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], ),
    sa.PrimaryKeyConstraint('login_attempt_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_attempt')
    op.drop_table('login_device')
    op.drop_table('bcrypt_login')
    op.drop_table('auth_device')
    op.drop_table('person')
    # ### end Alembic commands ###
